import {
  attribute,
  autoGeneratedHashKey,
  rangeKey,
  table,
} from "@aws/dynamodb-data-mapper-annotations";
import { ServerStatus, User } from "@mira-hq/model";

@table("MiraHq")
class Server {
  @autoGeneratedHashKey()
  readonly uuid?: string;
  @rangeKey()
  readonly serverName?: string;
  @attribute()
  readonly address?: string;
  @attribute()
  readonly status?: ServerStatus;
  @attribute()
  readonly uptime?: number;
  @attribute()
  readonly maxUptime?: number;
  @attribute()
  readonly playersOnline?: number;
  @attribute()
  readonly owned?: User;
}
